In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import load_digits
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split

In [27]:
data = load_digits()

In [28]:

X = data.data
y = data.target

In [29]:
X = X/64

In [30]:
X

array([[0.      , 0.      , 0.078125, ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.15625 , 0.      , 0.      ],
       [0.      , 0.      , 0.      , ..., 0.25    , 0.140625, 0.      ],
       ...,
       [0.      , 0.      , 0.015625, ..., 0.09375 , 0.      , 0.      ],
       [0.      , 0.      , 0.03125 , ..., 0.1875  , 0.      , 0.      ],
       [0.      , 0.      , 0.15625 , ..., 0.1875  , 0.015625, 0.      ]])

In [31]:
y

array([0, 1, 2, ..., 8, 9, 8])

In [32]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)

In [33]:
X_train

array([[0.      , 0.      , 0.078125, ..., 0.15625 , 0.      , 0.      ],
       [0.      , 0.      , 0.046875, ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.078125, ..., 0.25    , 0.171875, 0.03125 ],
       ...,
       [0.      , 0.      , 0.140625, ..., 0.25    , 0.03125 , 0.      ],
       [0.      , 0.      , 0.015625, ..., 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.015625, ..., 0.015625, 0.      , 0.      ]])

In [34]:
LR = LogisticRegression()
LR.fit(X_train,y_train)

LogisticRegression()

In [35]:
y_pred = LR.predict(X_test)

In [36]:
acc = accuracy_score(y_test,y_pred)
acc

0.9388888888888889

In [38]:
kf = KFold(n_splits= 5)

In [39]:
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [46]:
X = [2,3,4,5,6,7,8,9,10,12]
kf.split(X)

<generator object _BaseKFold.split at 0x1404de420>

In [47]:
for x,y in kf.split(X):
    print(x,"     ",y)

[2 3 4 5 6 7 8 9]       [0 1]
[0 1 4 5 6 7 8 9]       [2 3]
[0 1 2 3 6 7 8 9]       [4 5]
[0 1 2 3 4 5 8 9]       [6 7]
[0 1 2 3 4 5 6 7]       [8 9]


In [51]:
scores_LR = []
for train,test in kf.split(data.data):
    X_train,X_test,y_train,y_test = data.data[train],data.data[test],data.target[train],data.target[test]
    model = LogisticRegression()
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    scores_LR.append(acc)
scores_LR

/Users/surya/anaconda3/envs/Tf-metal/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/Users/surya/anaconda3/envs/Tf-metal/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/l

[0.9277777777777778,
 0.8666666666666667,
 0.9387186629526463,
 0.935933147632312,
 0.9080779944289693]