In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [6]:
df = pd.read_csv('spam.csv',encoding = 'latin-1')

In [7]:
df

v1                                                 v2 Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   
...    ...                                                ...        ...   
5567  spam  This is the 2nd time we have tried 2 contact u...        NaN   
5568   ham              Will Ì_ b going to esplanade fr home?        NaN   
5569   ham  Pity, * was in mood for that. So...any other s...        NaN   
5570   ham  The guy did some bitching but I acted like i'd...        NaN   
5571   ham                         Rofl. Its true to its name        NaN   

     Unnamed: 3 Unnamed: 4  
0           NaN        NaN  
1           NaN        NaN  
2           NaN        NaN  
3           NaN        NaN  
4           NaN        NaN  
...         ...        ...  
5567        NaN        NaN  
5568        NaN        NaN  
5569        NaN        NaN  
5570        NaN        NaN  
5571        NaN        NaN  

[5572 rows x 5 columns]

In [9]:
df = df.iloc[:,:-3]

In [12]:
df.nunique()

v1       2
v2    5169
dtype: int64

In [17]:
df.columns

Index(['v1', 'v2'], dtype='object')

In [18]:
df.rename(columns = {'v1':'Category'},inplace= True)

/var/folders/21/yhy2dhmx219b7cbcq243hmwc0000gn/T/ipykernel_20123/942117170.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'v1':'Category'},inplace= True)


In [22]:
df.rename(columns = {'v2':'Message'},inplace= True)

/var/folders/21/yhy2dhmx219b7cbcq243hmwc0000gn/T/ipykernel_20123/2395398442.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns = {'v2':'Message'},inplace= True)


In [23]:
df

Category                                            Message
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0              Will Ì_ b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [20]:
le = LabelEncoder()
df['Category'] = le.fit_transform(df['Category'])

/var/folders/21/yhy2dhmx219b7cbcq243hmwc0000gn/T/ipykernel_20123/2120877778.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = le.fit_transform(df['Category'])


In [21]:
df

Category                                                 v2
0            0  Go until jurong point, crazy.. Available only ...
1            0                      Ok lar... Joking wif u oni...
2            1  Free entry in 2 a wkly comp to win FA Cup fina...
3            0  U dun say so early hor... U c already then say...
4            0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567         1  This is the 2nd time we have tried 2 contact u...
5568         0              Will Ì_ b going to esplanade fr home?
5569         0  Pity, * was in mood for that. So...any other s...
5570         0  The guy did some bitching but I acted like i'd...
5571         0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [26]:
X = df.iloc[:,1].values
y = df.iloc[:,0].values

In [27]:
X

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=42,test_size=0.2)

In [57]:
count_vec = CountVectorizer()

In [31]:
count_vec.__doc__

'Convert a collection of text documents to a matrix of token counts.\n\n    This implementation produces a sparse representation of the counts using\n    scipy.sparse.csr_matrix.\n\n    If you do not provide an a-priori dictionary and you do not use an analyzer\n    that does some kind of feature selection then the number of features will\n    be equal to the vocabulary size found by analyzing the data.\n\n    For an efficiency comparision of the different feature extractors, see\n    :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.\n\n    Read more in the :ref:`User Guide <text_feature_extraction>`.\n\n    Parameters\n    ----------\n    input : {\'filename\', \'file\', \'content\'}, default=\'content\'\n        - If `\'filename\'`, the sequence passed as an argument to fit is\n          expected to be a list of filenames that need reading to fetch\n          the raw content to analyze.\n\n        - If `\'file\'`, the sequence items must have a \'read\' method (f

In [59]:
dir(CountVectorizer)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',


In [33]:
print("Convert a collection of text documents to a matrix of token counts.\n\n    This implementation produces a sparse representation of the counts using\n    scipy.sparse.csr_matrix.\n\n    If you do not provide an a-priori dictionary and you do not use an analyzer\n    that does some kind of feature selection then the number of features will\n    be equal to the vocabulary size found by analyzing the data.\n\n    For an efficiency comparision of the different feature extractors, see\n    :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.\n\n    Read more in the :ref:`User Guide <text_feature_extraction>`.\n\n    Parameters\n    ----------\n    input : {\'filename\', \'file\', \'content\'}, default=\'content\'\n        - If `\'filename\'`, the sequence passed as an argument to fit is\n          expected to be a list of filenames that need reading to fetch\n          the raw content to analyze.\n\n        - If `\'file\'`, the sequence items must have a \'read\' method (file-like\n          object) that is called to fetch the bytes in memory.\n\n        - If `\'content\'`, the input is expected to be a sequence of items that\n          can be of type string or byte.\n\n    encoding : str, default=\'utf-8\'\n        If bytes or files are given to analyze, this encoding is used to\n        decode.\n\n    decode_error : {\'strict\', \'ignore\', \'replace\'}, default=\'strict\'\n        Instruction on what to do if a byte sequence is given to analyze that\n        contains characters not of the given `encoding`. By default, it is\n        \'strict\', meaning that a UnicodeDecodeError will be raised. Other\n        values are \'ignore\' and \'replace\'.\n\n    strip_accents : {\'ascii\', \'unicode\'} or callable, default=None\n        Remove accents and perform other character normalization\n        during the preprocessing step.\n        \'ascii\' is a fast method that only works on characters that have\n        a direct ASCII mapping.\n        \'unicode\' is a slightly slower method that works on any characters.\n        None (default) means no character normalization is performed.\n\n        Both \'ascii\' and \'unicode\' use NFKD normalization from\n        :func:`unicodedata.normalize`.\n\n    lowercase : bool, default=True\n        Convert all characters to lowercase before tokenizing.\n\n    preprocessor : callable, default=None\n        Override the preprocessing (strip_accents and lowercase) stage while\n        preserving the tokenizing and n-grams generation steps.\n        Only applies if ``analyzer`` is not callable.\n\n    tokenizer : callable, default=None\n        Override the string tokenization step while preserving the\n        preprocessing and n-grams generation steps.\n        Only applies if ``analyzer == \'word\'``.\n\n    stop_words : {\'english\'}, list, default=None\n        If \'english\', a built-in stop word list for English is used.\n        There are several known issues with \'english\' and you should\n        consider an alternative (see :ref:`stop_words`).\n\n        If a list, that list is assumed to contain stop words, all of which\n        will be removed from the resulting tokens.\n        Only applies if ``analyzer == \'word\'``.\n\n        If None, no stop words will be used. In this case, setting `max_df`\n        to a higher value, such as in the range (0.7, 1.0), can automatically detect\n        and filter stop words based on intra corpus document frequency of terms.\n\n    token_pattern : str or None, default=       Regular expression denoting what constitutes a , only used\n        if ``analyzer == \'word\'``. The default regexp select tokens of 2\n        or more alphanumeric characters (punctuation is completely ignored\n        and always treated as a token separator).\n\n        If there is a capturing group in token_pattern then the\n        captured group content, not the entire match, becomes the token.\n        At most one capturing group is permitted.\n\n    ngram_range : tuple (min_n, max_n), default=(1, 1)\n        The lower and upper boundary of the range of n-values for different\n        word n-grams or char n-grams to be extracted. All values of n such\n        such that min_n <= n <= max_n will be used. For example an\n        ``ngram_range`` of ``(1, 1)`` means only unigrams, ``(1, 2)`` means\n        unigrams and bigrams, and ``(2, 2)`` means only bigrams.\n        Only applies if ``analyzer`` is not callable.\n\n    analyzer : {\'word\', \'char\', \'char_wb\'} or callable, default=\'word\'\n        Whether the feature should be made of word n-gram or character\n        n-grams.\n        Option \'char_wb\' creates character n-grams only from text inside\n        word boundaries; n-grams at the edges of words are padded with space.\n\n        If a callable is passed it is used to extract the sequence of features\n        out of the raw, unprocessed input.\n\n        .. versionchanged:: 0.21\n\n        Since v0.21, if ``input`` is ``filename`` or ``file``, the data is\n        first read from the file and then passed to the given callable\n        analyzer.\n\n    max_df : float in range [0.0, 1.0] or int, default=1.0\n        When building the vocabulary ignore terms that have a document\n        frequency strictly higher than the given threshold (corpus-specific\n        stop words).\n        If float, the parameter represents a proportion of documents, integer\n        absolute counts.\n        This parameter is ignored if vocabulary is not None.\n\n    min_df : float in range [0.0, 1.0] or int, default=1\n        When building the vocabulary ignore terms that have a document\n        frequency strictly lower than the given threshold. This value is also\n        called cut-off in the literature.\n        If float, the parameter represents a proportion of documents, integer\n        absolute counts.\n        This parameter is ignored if vocabulary is not None.\n\n    max_features : int, default=None\n        If not None, build a vocabulary that only consider the top\n        `max_features` ordered by term frequency across the corpus.\n        Otherwise, all features are used.\n\n        This parameter is ignored if vocabulary is not None.\n\n    vocabulary : Mapping or iterable, default=None\n        Either a Mapping (e.g., a dict) where keys are terms and values are\n        indices in the feature matrix, or an iterable over terms. If not\n        given, a vocabulary is determined from the input documents. Indices\n        in the mapping should not be repeated and should not have any gap\n        between 0 and the largest index.\n\n    binary : bool, default=False\n        If True, all non zero counts are set to 1. This is useful for discrete\n        probabilistic models that model binary events rather than integer\n        counts.\n\n    dtype : dtype, default=np.int64\n        Type of the matrix returned by fit_transform() or transform().\n\n    Attributes\n    ----------\n    vocabulary_ : dict\n        A mapping of terms to feature indices.\n\n    fixed_vocabulary_ : bool\n        True if a fixed vocabulary of term to indices mapping\n        is provided by the user.\n\n    stop_words_ : set\n        Terms that were ignored because they either:\n\n          - occurred in too many documents (`max_df`)\n          - occurred in too few documents (`min_df`)\n          - were cut off by feature selection (`max_features`).\n\n        This is only available if no vocabulary was given.\n\n    See Also\n    --------\n    HashingVectorizer : Convert a collection of text documents to a\n        matrix of token counts.\n\n    TfidfVectorizer : Convert a collection of raw documents to a matrix\n        of TF-IDF features.\n\n    Notes\n    -----\n    The ``stop_words_`` attribute can get large and increase the model size\n    when pickling. This attribute is provided only for introspection and can\n    be safely removed using delattr or set to None before pickling.\n\n    Examples\n    --------\n    >>> from sklearn.feature_extraction.text import CountVectorizer\n    >>> corpus = [\n    ...     \'This is the first document.\',\n    ...     \'This document is the second document.\',\n    ...     \'And this is the third one.\',\n    ...     \'Is this the first document?\',\n    ... ]\n    >>> vectorizer = CountVectorizer()\n    >>> X = vectorizer.fit_transform(corpus)\n    >>> vectorizer.get_feature_names_out()\n    array([\'and\', \'document\', \'first\', \'is\', \'one\', \'second\', \'the\', \'third\',\n           \'this\'], ...)\n    >>> print(X.toarray())\n    [[0 1 1 1 0 0 1 0 1]\n     [0 2 0 1 0 1 1 0 1]\n     [1 0 0 1 1 0 1 1 1]\n     [0 1 1 1 0 0 1 0 1]]\n    >>> vectorizer2 = CountVectorizer(analyzer=\'word\', ngram_range=(2, 2))\n    >>> X2 = vectorizer2.fit_transform(corpus)\n    >>> vectorizer2.get_feature_names_out()\n    array([\'and this\', \'document is\', \'first document\', \'is the\', \'is this\',\n           \'second document\', \'the first\', \'the second\', \'the third\', \'third one\',\n           \'this document\', \'this is\', \'this the\'], ...)\n     >>> print(X2.toarray())\n     [[0 0 1 1 0 0 1 0 0 0 0 1 0]\n     [0 1 0 1 0 1 0 1 0 0 1 0 0]\n     [1 0 0 1 0 0 0 0 1 1 0 1 0]\n     [0 0 1 0 1 0 1 0 0 0 0 0 1]]\n    '")

Convert a collection of text documents to a matrix of token counts.

    This implementation produces a sparse representation of the counts using
    scipy.sparse.csr_matrix.

    If you do not provide an a-priori dictionary and you do not use an analyzer
    that does some kind of feature selection then the number of features will
    be equal to the vocabulary size found by analyzing the data.

    For an efficiency comparision of the different feature extractors, see
    :ref:`sphx_glr_auto_examples_text_plot_hashing_vs_dict_vectorizer.py`.

    Read more in the :ref:`User Guide <text_feature_extraction>`.

    Parameters
    ----------
    input : {'filename', 'file', 'content'}, default='content'
        - If `'filename'`, the sequence passed as an argument to fit is
          expected to be a list of filenames that need reading to fetch
          the raw content to analyze.

        - If `'file'`, the sequence items must have a 'read' method (file-like
          object) that is c

In [36]:
X_train

array(["No I'm in the same boat. Still here at my moms. Check me out on yo. I'm half naked.",
       '(Bank of Granite issues Strong-Buy) EXPLOSIVE PICK FOR OUR MEMBERS *****UP OVER 300% *********** Nasdaq Symbol CDGT That is a $5.00 per..',
       'They r giving a second chance to rahul dengra.', ...,
       "Prabha..i'm soryda..realy..frm heart i'm sory",
       'Nt joking seriously i told',
       'In work now. Going have in few min.'], dtype=object)

In [34]:
X_train_count = count_vec.fit_transform(X_train)
X_train_count

<4457x7735 sparse matrix of type '<class 'numpy.int64'>'
	with 58978 stored elements in Compressed Sparse Row format>

In [35]:
count_vec.get_feature_names_out()

array(['00', '000', '000pes', ..., 'ûïharry', 'ûò', 'ûówell'],
      dtype=object)

In [40]:
X_train_count.shape

(4457, 7735)

In [43]:
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [42]:
multi_nb = MultinomialNB()

In [44]:
multi_nb.fit(X_train_count,y_train)

MultinomialNB()

In [45]:
multi_nb.class_count_

array([3860.,  597.])

In [47]:
X_test_count = count_vec.transform(X_test)

In [48]:
X_test_count.shape

(1115, 7735)

In [49]:
y_pred = multi_nb.predict(X_test_count)

In [50]:
y_pred

array([0, 0, 1, ..., 0, 0, 1])

In [51]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_pred)
acc

0.9838565022421525

In [46]:
emails = ['Hey mohan, can we get together to watch footbal game tomorrow?','Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!']

In [52]:
emails_count = count_vec.transform(emails)

In [53]:
emails_count.shape

(2, 7735)

In [55]:
y_pred = multi_nb.predict(emails_count)


In [56]:
y_pred

array([0, 1])

In [63]:
X_train

array(["No I'm in the same boat. Still here at my moms. Check me out on yo. I'm half naked.",
       '(Bank of Granite issues Strong-Buy) EXPLOSIVE PICK FOR OUR MEMBERS *****UP OVER 300% *********** Nasdaq Symbol CDGT That is a $5.00 per..',
       'They r giving a second chance to rahul dengra.', ...,
       "Prabha..i'm soryda..realy..frm heart i'm sory",
       'Nt joking seriously i told',
       'In work now. Going have in few min.'], dtype=object)

In [64]:
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [67]:
from sklearn.pipeline import Pipeline
model = Pipeline([('vectorizer',CountVectorizer()),('nb',MultinomialNB())])

In [68]:
model.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [69]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 1, ..., 0, 0, 1])