In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('logis_reg_dataset.csv')
df

m1  m2  m3 pass/fail
0  70  65  58         P
1  32  40  12         F
2  82  12  70         F
3  65  58  48         P
4  70  75  92         P
5  68  69  63         P
6  32  15  60         F
7  18  20  31         F
8  50  60  70         P
9  89  92  98         P

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [15]:
X[0]

array([0.73239437, 0.6625    , 0.53488372])

In [7]:
y

array(['P', 'F', 'F', 'P', 'P', 'P', 'F', 'F', 'P', 'P'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 0 1 1 1 0 0 1 1]


In [13]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X = ms.fit_transform(X)
X

array([[0.73239437, 0.6625    , 0.53488372],
       [0.1971831 , 0.35      , 0.        ],
       [0.90140845, 0.        , 0.6744186 ],
       [0.66197183, 0.575     , 0.41860465],
       [0.73239437, 0.7875    , 0.93023256],
       [0.70422535, 0.7125    , 0.59302326],
       [0.1971831 , 0.0375    , 0.55813953],
       [0.        , 0.1       , 0.22093023],
       [0.45070423, 0.6       , 0.6744186 ],
       [1.        , 1.        , 1.        ]])

In [14]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X, y)


LogisticRegression()

In [17]:
log_reg.predict([X[0]])

array([1])