In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('logis_reg_dataset.csv')
df

m1  m2  m3 pass/fail
0  70  65  58         P
1  32  40  12         F
2  82  12  70         F
3  65  58  48         P
4  70  75  92         P
5  68  69  63         P
6  32  15  60         F
7  18  20  31         F
8  50  60  70         P
9  89  92  98         P

In [4]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [5]:
X[0]

array([70, 65, 58])

In [6]:
y

array(['P', 'F', 'F', 'P', 'P', 'P', 'F', 'F', 'P', 'P'], dtype=object)

In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[1 0 0 1 1 1 0 0 1 1]


In [8]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X = ms.fit_transform(X)
X

array([[0.73239437, 0.6625    , 0.53488372],
       [0.1971831 , 0.35      , 0.        ],
       [0.90140845, 0.        , 0.6744186 ],
       [0.66197183, 0.575     , 0.41860465],
       [0.73239437, 0.7875    , 0.93023256],
       [0.70422535, 0.7125    , 0.59302326],
       [0.1971831 , 0.0375    , 0.55813953],
       [0.        , 0.1       , 0.22093023],
       [0.45070423, 0.6       , 0.6744186 ],
       [1.        , 1.        , 1.        ]])

In [9]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression()
log_reg.fit(X, y)


LogisticRegression()

In [10]:
log_reg.predict([X[0]])

array([1])

In [11]:
y_pred = log_reg.predict(X)

In [12]:
from sklearn.metrics import confusion_matrix
c_mat = confusion_matrix(y,y_pred)
print(c_mat)

[[3 1]
 [0 6]]


In [16]:
from sklearn.datasets import load_diabetes
df = load_diabetes()
data = df.data
target = df.target

In [17]:
data

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990749, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06833155, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286131, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04688253,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452873, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00422151,  0.00306441]])

In [18]:
type(data)

numpy.ndarray

In [19]:
target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28