## Write a NumPy program to compute the addition of two matrices.

In [1]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[11, 12, 13],
                    [14, 15, 16],
                    [17, 18, 19]])
result = matrix1 + matrix2

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Addition:")
print(result)

Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Result of Matrix Addition:
[[12 14 16]
 [18 20 22]
 [24 26 28]]


## Write a NumPy program to compute the multiplication of two matrices.

In [4]:
import numpy as np
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[11, 12, 13],
                    [14, 15, 16],
                    [17, 18, 19]])

result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nResult of Matrix Multiplication:")
print(result_matrix)
print(type(result_matrix))


Matrix 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
[[11 12 13]
 [14 15 16]
 [17 18 19]]

Result of Matrix Multiplication:
[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
<class 'numpy.ndarray'>


 ## Write a NumPy program to compute the dot product of two vectors.

In [6]:
import numpy as np
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
dot_prod = np.dot(vector1, vector2)
print(type(vector1))
print(type(dot_prod)) 
print("Vector 1 : ",vector1)
print("Vector 2 : ",vector2)
print(dot_prod)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
Vector 1 :  [1 2 3]
Vector 2 :  [4 5 6]
32


## Write a NumPy program to find the transpose of a matrix.

In [7]:
import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])
transpose = np.transpose(matrix)
print("Original matrix : ",matrix)
print("Transpose matrix : ",transpose)


Original matrix :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose matrix :  [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Write a NumPy program to compute the determinant of a matrix.

In [9]:
import numpy as np
matrix = np.array([[1, 2], [3, 4]])
print("Original matrix : ",matrix)
det = np.linalg.det(matrix)
print(det)

Original matrix :  [[1 2]
 [3 4]]
-2.0000000000000004


## Write a NumPy program to compute the inverse of a square matrix.

In [10]:
import numpy as np
matrix = np.array([[1,2],[3,4]])
print("Original matrix : ", matrix)
rev_mat = np.linalg.inv(matrix)
print("Reverse matrix : ", rev_mat)

Original matrix :  [[1 2]
 [3 4]]
Reverse matrix :  [[-2.   1. ]
 [ 1.5 -0.5]]
