In [4]:
import numpy as np

In [5]:
a = [1,2,3,4,5,6,7,8,9,10]
print(type(a))
print(sum(a))
a = np.array(a)
print(type(a))

<class 'list'>
55
<class 'numpy.ndarray'>


In [9]:
b = np.zeros((3,4))
print(b)
c = np.arange(10,25,5)
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20]


In [10]:
d = np.array([[1,2],[3,4],[5,6]])

In [11]:
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
d.shape
d.ndim

2