In [4]:
import numpy as np

In [5]:
a = [1,2,3,4,5,6,7,8,9,10]
print(type(a))
print(sum(a))
a = np.array(a)
print(type(a))

<class 'list'>
55
<class 'numpy.ndarray'>


In [9]:
b = np.zeros((3,4))
print(b)
c = np.arange(10,25,5)
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[10 15 20]


In [10]:
d = np.array([[1,2],[3,4],[5,6]])

In [11]:
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
d.shape
d.ndim

2

In [23]:
arr1 = [1,2,3,4,5,6,7,8,9,10,11,12]
print(type(arr1))
arr1 = np.array(arr1)
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)
arr1 = arr1.reshape(3,2,2)
print(arr1)
print(arr1.strides)
print(arr1.ndim)


<class 'list'>
<class 'numpy.ndarray'>
1
(12,)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(32, 16, 8)
3


In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
arr2 = np.array([[7,8,9],[10,11,12]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
arr3 = np.concatenate((arr1, arr2),axis = 1)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
arr4 = np.concatenate((arr1, arr2),axis =0)
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[ 7  8  9]
 [10 11 12]]
2
(2, 3)
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
2
(2, 6)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
