# Logistic Regression

# Data Preprocessing

## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [2]:
irisdata = pd.read_csv('iris.csv',names = ['A', 'B', 'C','D','class'])
irisdata 

FileNotFoundError: [Errno 2] No such file or directory: 'iris.csv'

In [ ]:

irisdata['class'].value_counts()


Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: class, dtype: int64

In [ ]:
irisdata = irisdata.iloc[:100,:]
irisdata 

A    B    C    D            class
0   5.1  3.5  1.4  0.2      Iris-setosa
1   4.9  3.0  1.4  0.2      Iris-setosa
2   4.7  3.2  1.3  0.2      Iris-setosa
3   4.6  3.1  1.5  0.2      Iris-setosa
4   5.0  3.6  1.4  0.2      Iris-setosa
..  ...  ...  ...  ...              ...
95  5.7  3.0  4.2  1.2  Iris-versicolor
96  5.7  2.9  4.2  1.3  Iris-versicolor
97  6.2  2.9  4.3  1.3  Iris-versicolor
98  5.1  2.5  3.0  1.1  Iris-versicolor
99  5.7  2.8  4.1  1.3  Iris-versicolor

[100 rows x 5 columns]

In [ ]:
irisdata['class'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Name: class, dtype: int64

In [ ]:
def categorise(x):
    if x == "Iris-setosa":
        x = 1
    else:
        x = 0
    return x 
irisdata['class'] = irisdata['class'].apply(categorise)
irisdata['class'].value_counts()

/var/folders/21/yhy2dhmx219b7cbcq243hmwc0000gn/T/ipykernel_40909/3199066530.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  irisdata['class'] = irisdata['class'].apply(categorise)


1    50
0    50
Name: class, dtype: int64

In [ ]:
irisdata

A    B    C    D  class
0   5.1  3.5  1.4  0.2      1
1   4.9  3.0  1.4  0.2      1
2   4.7  3.2  1.3  0.2      1
3   4.6  3.1  1.5  0.2      1
4   5.0  3.6  1.4  0.2      1
..  ...  ...  ...  ...    ...
95  5.7  3.0  4.2  1.2      0
96  5.7  2.9  4.2  1.3      0
97  6.2  2.9  4.3  1.3      0
98  5.1  2.5  3.0  1.1      0
99  5.7  2.8  4.1  1.3      0

[100 rows x 5 columns]

In [ ]:
X = irisdata.iloc[:,:-1].values
Y = irisdata.iloc[:,-1].values

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [ ]:
X_train

array([[5.3, 3.7, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.8, 2.8, 4.8, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.6, 4.4, 1.2],
       [6.2, 2.2, 4.5, 1.5],
       [6.4, 3.2, 4.5, 1.5],
       [5.2, 3.5, 1.5, 0.2],
       [5.7, 3.8, 1.7, 0.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.1, 2.9, 4.7, 1.4],
       [6.4, 2.9, 4.3, 1.3],
       [4.9, 3. , 1.4, 0.2],
       [5.9, 3. , 4.2, 1.5],
       [4.4, 3.2, 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5. , 3.5, 1.3, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [6.1, 3. , 4.6, 1.4],
       [5.2, 2.7, 3.9, 1.4],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.2, 3.4, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [4.8, 3.4, 1.6, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [6.9, 3

In [ ]:
X_test

array([[5. , 3.4, 1.6, 0.4],
       [6.7, 3.1, 4.7, 1.5],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [5. , 2.3, 3.3, 1. ],
       [5.4, 3.9, 1.3, 0.4],
       [6.1, 2.8, 4.7, 1.2],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 3. , 4.2, 1.2],
       [5.5, 2.3, 4. , 1.3],
       [5.8, 2.6, 4. , 1.2],
       [6. , 2.9, 4.5, 1.5],
       [4.3, 3. , 1.1, 0.1],
       [5. , 3.4, 1.5, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [6. , 2.2, 4. , 1. ],
       [4.6, 3.1, 1.5, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [4.8, 3. , 1.4, 0.3]])

In [ ]:
Y_train


array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1])

In [ ]:
Y_train.shape

(75,)

In [ ]:
Y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1])

In [ ]:
Y_test.shape

(25,)

In [ ]:
X_train.shape

(75, 4)

## Feature Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)


In [ ]:
X_train

array([[0.34615385, 0.70833333, 0.07692308, 0.05882353],
       [0.07692308, 0.58333333, 0.05128205, 0.11764706],
       [0.5       , 0.33333333, 0.74358974, 0.70588235],
       [0.53846154, 0.29166667, 0.69230769, 0.64705882],
       [0.92307692, 0.33333333, 0.92307692, 0.76470588],
       [0.23076923, 0.        , 0.58974359, 0.52941176],
       [0.42307692, 0.16666667, 0.66666667, 0.58823529],
       [0.42307692, 0.25      , 0.82051282, 0.64705882],
       [0.69230769, 0.08333333, 0.84615385, 0.82352941],
       [0.76923077, 0.5       , 0.84615385, 0.82352941],
       [0.30769231, 0.625     , 0.07692308, 0.05882353],
       [0.5       , 0.75      , 0.12820513, 0.11764706],
       [0.73076923, 0.54166667, 0.8974359 , 0.88235294],
       [0.65384615, 0.375     , 0.8974359 , 0.76470588],
       [0.76923077, 0.375     , 0.79487179, 0.70588235],
       [0.19230769, 0.41666667, 0.05128205, 0.05882353],
       [0.57692308, 0.41666667, 0.76923077, 0.82352941],
       [0.        , 0.5       ,

In [ ]:
X_test

array([[0.29166667, 0.6       , 0.16216216, 0.21428571],
       [1.        , 0.45      , 1.        , 1.        ],
       [0.16666667, 0.5       , 0.08108108, 0.07142857],
       [0.58333333, 0.3       , 0.94594595, 0.85714286],
       [0.95833333, 0.4       , 0.91891892, 0.92857143],
       [0.29166667, 0.05      , 0.62162162, 0.64285714],
       [0.45833333, 0.85      , 0.08108108, 0.21428571],
       [0.75      , 0.3       , 1.        , 0.78571429],
       [0.91666667, 0.3       , 0.97297297, 1.        ],
       [0.58333333, 0.4       , 0.86486486, 0.78571429],
       [0.5       , 0.05      , 0.81081081, 0.85714286],
       [0.625     , 0.2       , 0.81081081, 0.78571429],
       [0.70833333, 0.35      , 0.94594595, 1.        ],
       [0.        , 0.4       , 0.02702703, 0.        ],
       [0.29166667, 0.6       , 0.13513514, 0.07142857],
       [0.20833333, 0.45      , 0.16216216, 0.07142857],
       [0.125     , 0.7       , 0.        , 0.07142857],
       [0.20833333, 0.6       ,

In [ ]:
Y_train

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1])

In [ ]:
Y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1])

In [ ]:
unique_values, counts = np.unique(Y_train, return_counts=True)

# Print the unique values and their corresponding counts
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")

Value: 0, Count: 38
Value: 1, Count: 37


In [ ]:
unique_values,counts = np.unique(Y_test,return_counts = True)
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")


Value: 0, Count: 12
Value: 1, Count: 13


## Training the Logistic Regression model on the Training set

In [ ]:
class LogisticRegression:
    def __init__(self,learning_rate = 0.01,num_iterations = 1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def fit(self,X,Y):
        num_samples,num_features = X.shape
        print(num_samples,num_features)
        self.weights = np.zeros(num_features)
        self.bias = 0

        for i in range(self.num_iterations):
            Y_pred = self.predicted(X)
            dw = (1/num_samples)*np.dot(X.T,(Y_pred - Y))
            db = (1/num_samples)*np.sum(Y_pred - Y)
            
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate*db
            
    def predicted(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        pred = self.sigmoid(linear_model)
        return pred
    
    def test(self,X,Y):
        global Y_predtest
        Y_predtest = self.predicted(X)
        print(Y_predtest)
        Y_values = Y_predtest
        correct = 0
        total = len(Y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i]>0.5:
                Y_predtest[i] =1
            else:
                Y_predtest[i]=0
        for i in range(len(Y)):
            if Y[i] == Y_predtest[i]:
                correct+=1
        print("Accuracy: ",correct/total) 
            
                
        
                

In [ ]:
lgreg = LogisticRegression()
lgreg.fit(X_train,Y_train)


75 4


In [ ]:
print(lgreg.weights)
print(lgreg.bias)

[-0.40408166  0.73567234 -1.13636661 -1.02187534]
0.46668817431957194


In [ ]:
print(lgreg.test(X_test, Y_test))


[0.5955568  0.14621729 0.64612482 0.18255099 0.16528752 0.27334933
 0.64467065 0.17437392 0.14057195 0.22089423 0.18304671 0.20375173
 0.15991405 0.67485892 0.63730366 0.61213376 0.70227556 0.61644907
 0.69093158 0.62515692 0.56900357 0.19815996 0.62730591 0.19577031
 0.60059402]
Accuracy:  1.0
None


In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
cm = confusion_matrix(Y_test,Y_predtest)
print(cm)
print(precision_score(Y_test,Y_predtest))
print(accuracy_score(Y_test,Y_predtest))
print(recall_score(Y_test,Y_predtest))

[[12  0]
 [ 0 13]]
1.0
1.0
1.0


In [ ]:
import pickle

In [ ]:

with open('mnist.pkl', 'rb') as f:
    data = pickle.load(f)


FileNotFoundError: [Errno 2] No such file or directory: 'mnist.pkl'