# Logistic Regression

# Data Preprocessing

## Importing the libraries

In [63]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Importing the dataset

In [64]:
irisdata = pd.read_csv('iris.csv')
irisdata 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [65]:
irisdata['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [66]:
irisdata = irisdata.iloc[:100,:]
irisdata 

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0     1            5.1           3.5            1.4           0.2   
1     2            4.9           3.0            1.4           0.2   
2     3            4.7           3.2            1.3           0.2   
3     4            4.6           3.1            1.5           0.2   
4     5            5.0           3.6            1.4           0.2   
..  ...            ...           ...            ...           ...   
95   96            5.7           3.0            4.2           1.2   
96   97            5.7           2.9            4.2           1.3   
97   98            6.2           2.9            4.3           1.3   
98   99            5.1           2.5            3.0           1.1   
99  100            5.7           2.8            4.1           1.3   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
95  Iris-versicolor  
96  Iris-versicolor  
97  Iris-versicolor  
98  Iris-versicolor  
99  Iris-versicolor  

[100 rows x 6 columns]

In [67]:
irisdata['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Name: Species, dtype: int64

In [68]:
irisdata['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
           ...       
95    Iris-versicolor
96    Iris-versicolor
97    Iris-versicolor
98    Iris-versicolor
99    Iris-versicolor
Name: Species, Length: 100, dtype: object

In [69]:
def categorise(x):
    if x == "Iris-setosa":
        x = 1
    else:
        x = 0
    return x 
irisdata['Species'] = irisdata['Species'].apply(categorise)
irisdata['Species'].value_counts()

/var/folders/21/yhy2dhmx219b7cbcq243hmwc0000gn/T/ipykernel_47173/3904547442.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  irisdata['Species'] = irisdata['Species'].apply(categorise)


1    50
0    50
Name: Species, dtype: int64

In [70]:
irisdata

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1            5.1           3.5            1.4           0.2        1
1     2            4.9           3.0            1.4           0.2        1
2     3            4.7           3.2            1.3           0.2        1
3     4            4.6           3.1            1.5           0.2        1
4     5            5.0           3.6            1.4           0.2        1
..  ...            ...           ...            ...           ...      ...
95   96            5.7           3.0            4.2           1.2        0
96   97            5.7           2.9            4.2           1.3        0
97   98            6.2           2.9            4.3           1.3        0
98   99            5.1           2.5            3.0           1.1        0
99  100            5.7           2.8            4.1           1.3        0

[100 rows x 6 columns]

In [71]:
X = irisdata.iloc[:,:-1].values
Y = irisdata.iloc[:,-1].values

In [72]:
X

array([[  1. ,   5.1,   3.5,   1.4,   0.2],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [  3. ,   4.7,   3.2,   1.3,   0.2],
       [  4. ,   4.6,   3.1,   1.5,   0.2],
       [  5. ,   5. ,   3.6,   1.4,   0.2],
       [  6. ,   5.4,   3.9,   1.7,   0.4],
       [  7. ,   4.6,   3.4,   1.4,   0.3],
       [  8. ,   5. ,   3.4,   1.5,   0.2],
       [  9. ,   4.4,   2.9,   1.4,   0.2],
       [ 10. ,   4.9,   3.1,   1.5,   0.1],
       [ 11. ,   5.4,   3.7,   1.5,   0.2],
       [ 12. ,   4.8,   3.4,   1.6,   0.2],
       [ 13. ,   4.8,   3. ,   1.4,   0.1],
       [ 14. ,   4.3,   3. ,   1.1,   0.1],
       [ 15. ,   5.8,   4. ,   1.2,   0.2],
       [ 16. ,   5.7,   4.4,   1.5,   0.4],
       [ 17. ,   5.4,   3.9,   1.3,   0.4],
       [ 18. ,   5.1,   3.5,   1.4,   0.3],
       [ 19. ,   5.7,   3.8,   1.7,   0.3],
       [ 20. ,   5.1,   3.8,   1.5,   0.3],
       [ 21. ,   5.4,   3.4,   1.7,   0.2],
       [ 22. ,   5.1,   3.7,   1.5,   0.4],
       [ 23. ,   4.6,   3.6,   1

In [73]:
Y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Splitting the dataset into the Training set and Test set

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [75]:
X_train

array([[ 49. ,   5.3,   3.7,   1.5,   0.2],
       [  7. ,   4.6,   3.4,   1.4,   0.3],
       [100. ,   5.7,   2.8,   4.1,   1.3],
       [ 83. ,   5.8,   2.7,   3.9,   1.2],
       [ 77. ,   6.8,   2.8,   4.8,   1.4],
       [ 61. ,   5. ,   2. ,   3.5,   1. ],
       [ 81. ,   5.5,   2.4,   3.8,   1.1],
       [ 91. ,   5.5,   2.6,   4.4,   1.2],
       [ 69. ,   6.2,   2.2,   4.5,   1.5],
       [ 52. ,   6.4,   3.2,   4.5,   1.5],
       [ 28. ,   5.2,   3.5,   1.5,   0.2],
       [ 19. ,   5.7,   3.8,   1.7,   0.3],
       [ 57. ,   6.3,   3.3,   4.7,   1.6],
       [ 64. ,   6.1,   2.9,   4.7,   1.4],
       [ 75. ,   6.4,   2.9,   4.3,   1.3],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [ 62. ,   5.9,   3. ,   4.2,   1.5],
       [ 43. ,   4.4,   3.2,   1.3,   0.2],
       [ 42. ,   4.5,   2.3,   1.3,   0.3],
       [  5. ,   5. ,   3.6,   1.4,   0.2],
       [ 16. ,   5.7,   4.4,   1.5,   0.4],
       [ 18. ,   5.1,   3.5,   1.4,   0.3],
       [ 41. ,   5. ,   3.5,   1

In [76]:
X_test

array([[27. ,  5. ,  3.4,  1.6,  0.4],
       [87. ,  6.7,  3.1,  4.7,  1.5],
       [ 3. ,  4.7,  3.2,  1.3,  0.2],
       [56. ,  5.7,  2.8,  4.5,  1.3],
       [76. ,  6.6,  3. ,  4.4,  1.4],
       [94. ,  5. ,  2.3,  3.3,  1. ],
       [17. ,  5.4,  3.9,  1.3,  0.4],
       [74. ,  6.1,  2.8,  4.7,  1.2],
       [55. ,  6.5,  2.8,  4.6,  1.5],
       [96. ,  5.7,  3. ,  4.2,  1.2],
       [54. ,  5.5,  2.3,  4. ,  1.3],
       [93. ,  5.8,  2.6,  4. ,  1.2],
       [79. ,  6. ,  2.9,  4.5,  1.5],
       [14. ,  4.3,  3. ,  1.1,  0.1],
       [ 8. ,  5. ,  3.4,  1.5,  0.2],
       [31. ,  4.8,  3.1,  1.6,  0.2],
       [23. ,  4.6,  3.6,  1. ,  0.2],
       [25. ,  4.8,  3.4,  1.9,  0.2],
       [34. ,  5.5,  4.2,  1.4,  0.2],
       [ 9. ,  4.4,  2.9,  1.4,  0.2],
       [44. ,  5. ,  3.5,  1.6,  0.6],
       [63. ,  6. ,  2.2,  4. ,  1. ],
       [ 4. ,  4.6,  3.1,  1.5,  0.2],
       [72. ,  6.1,  2.8,  4. ,  1.3],
       [46. ,  4.8,  3. ,  1.4,  0.3]])

In [77]:
Y_train


array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1])

In [78]:
Y_train.shape

(75,)

In [79]:
Y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1])

In [80]:
Y_test.shape

(25,)

In [81]:
X_train.shape

(75, 5)

In [82]:
X_train

array([[ 49. ,   5.3,   3.7,   1.5,   0.2],
       [  7. ,   4.6,   3.4,   1.4,   0.3],
       [100. ,   5.7,   2.8,   4.1,   1.3],
       [ 83. ,   5.8,   2.7,   3.9,   1.2],
       [ 77. ,   6.8,   2.8,   4.8,   1.4],
       [ 61. ,   5. ,   2. ,   3.5,   1. ],
       [ 81. ,   5.5,   2.4,   3.8,   1.1],
       [ 91. ,   5.5,   2.6,   4.4,   1.2],
       [ 69. ,   6.2,   2.2,   4.5,   1.5],
       [ 52. ,   6.4,   3.2,   4.5,   1.5],
       [ 28. ,   5.2,   3.5,   1.5,   0.2],
       [ 19. ,   5.7,   3.8,   1.7,   0.3],
       [ 57. ,   6.3,   3.3,   4.7,   1.6],
       [ 64. ,   6.1,   2.9,   4.7,   1.4],
       [ 75. ,   6.4,   2.9,   4.3,   1.3],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [ 62. ,   5.9,   3. ,   4.2,   1.5],
       [ 43. ,   4.4,   3.2,   1.3,   0.2],
       [ 42. ,   4.5,   2.3,   1.3,   0.3],
       [  5. ,   5. ,   3.6,   1.4,   0.2],
       [ 16. ,   5.7,   4.4,   1.5,   0.4],
       [ 18. ,   5.1,   3.5,   1.4,   0.3],
       [ 41. ,   5. ,   3.5,   1

## Feature Scaling

In [83]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)


In [84]:
X_train

array([[0.48484848, 0.34615385, 0.70833333, 0.07692308, 0.05882353],
       [0.06060606, 0.07692308, 0.58333333, 0.05128205, 0.11764706],
       [1.        , 0.5       , 0.33333333, 0.74358974, 0.70588235],
       [0.82828283, 0.53846154, 0.29166667, 0.69230769, 0.64705882],
       [0.76767677, 0.92307692, 0.33333333, 0.92307692, 0.76470588],
       [0.60606061, 0.23076923, 0.        , 0.58974359, 0.52941176],
       [0.80808081, 0.42307692, 0.16666667, 0.66666667, 0.58823529],
       [0.90909091, 0.42307692, 0.25      , 0.82051282, 0.64705882],
       [0.68686869, 0.69230769, 0.08333333, 0.84615385, 0.82352941],
       [0.51515152, 0.76923077, 0.5       , 0.84615385, 0.82352941],
       [0.27272727, 0.30769231, 0.625     , 0.07692308, 0.05882353],
       [0.18181818, 0.5       , 0.75      , 0.12820513, 0.11764706],
       [0.56565657, 0.73076923, 0.54166667, 0.8974359 , 0.88235294],
       [0.63636364, 0.65384615, 0.375     , 0.8974359 , 0.76470588],
       [0.74747475, 0.76923077, 0.

In [85]:
X_test

array([[0.25806452, 0.29166667, 0.6       , 0.16216216, 0.21428571],
       [0.90322581, 1.        , 0.45      , 1.        , 1.        ],
       [0.        , 0.16666667, 0.5       , 0.08108108, 0.07142857],
       [0.56989247, 0.58333333, 0.3       , 0.94594595, 0.85714286],
       [0.78494624, 0.95833333, 0.4       , 0.91891892, 0.92857143],
       [0.97849462, 0.29166667, 0.05      , 0.62162162, 0.64285714],
       [0.15053763, 0.45833333, 0.85      , 0.08108108, 0.21428571],
       [0.76344086, 0.75      , 0.3       , 1.        , 0.78571429],
       [0.55913978, 0.91666667, 0.3       , 0.97297297, 1.        ],
       [1.        , 0.58333333, 0.4       , 0.86486486, 0.78571429],
       [0.5483871 , 0.5       , 0.05      , 0.81081081, 0.85714286],
       [0.96774194, 0.625     , 0.2       , 0.81081081, 0.78571429],
       [0.8172043 , 0.70833333, 0.35      , 0.94594595, 1.        ],
       [0.11827957, 0.        , 0.4       , 0.02702703, 0.        ],
       [0.05376344, 0.29166667, 0.

In [86]:
Y_train

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1])

In [87]:
Y_test

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 1])

In [88]:
unique_values, counts = np.unique(Y_train, return_counts=True)

# Print the unique values and their corresponding counts
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")

Value: 0, Count: 38
Value: 1, Count: 37


In [89]:
unique_values,counts = np.unique(Y_test,return_counts = True)
for value, count in zip(unique_values, counts):
    print(f"Value: {value}, Count: {count}")


Value: 0, Count: 12
Value: 1, Count: 13


## Training the Logistic Regression model on the Training set

In [90]:
class LogisticRegression:
    def __init__(self,learning_rate = 0.01,num_iterations = 1000):
        self.learning_rate = learning_rate
        self.num_iterations = num_iterations
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def fit(self,X,Y):
        num_samples,num_features = X.shape
        print(num_samples,num_features)
        self.weights = np.zeros(num_features)
        self.bias = 0

        for i in range(self.num_iterations):
            Y_pred = self.predicted(X)
            dw = (1/num_samples)*np.dot(X.T,(Y_pred - Y))
            db = (1/num_samples)*np.sum(Y_pred - Y)
            
            self.weights -= self.learning_rate * dw
            self.bias -= self.learning_rate*db
            
    def predicted(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        pred = self.sigmoid(linear_model)
        return pred
    
    def test(self,X,Y):
        global Y_predtest
        Y_predtest = self.predicted(X)
        print(Y_predtest)
        Y_values = Y_predtest
        correct = 0
        total = len(Y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i]>0.5:
                Y_predtest[i] =1
            else:
                Y_predtest[i]=0
        for i in range(len(Y)):
            if Y[i] == Y_predtest[i]:
                correct+=1
        print("Accuracy: ",correct/total) 
            
                
        
                

In [91]:
lgreg = LogisticRegression()
lgreg.fit(X_train,Y_train)


75 5


In [92]:
print(lgreg.weights)
print(lgreg.bias)

[-0.59421133 -0.34134347  0.77201815 -1.0442842  -0.93645331]
0.593168363178588


In [93]:
print(lgreg.test(X_test, Y_test))


[0.60670052 0.12806114 0.68367784 0.18190551 0.15177517 0.21410155
 0.67219802 0.15909891 0.14518389 0.17794948 0.18032436 0.16474853
 0.14328225 0.69071597 0.67191627 0.61166778 0.71017543 0.62803481
 0.69352673 0.65272314 0.55716557 0.18532151 0.66452169 0.179242
 0.57674976]
Accuracy:  1.0
None


In [94]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score
cm = confusion_matrix(Y_test,Y_predtest)
print(cm)
print(precision_score(Y_test,Y_predtest))
print(accuracy_score(Y_test,Y_predtest))
print(recall_score(Y_test,Y_predtest))

[[12  0]
 [ 0 13]]
1.0
1.0
1.0
