## Logistic Regression

In [205]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [206]:
data = pd.read_csv('iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [207]:
def convert(x):
    if x=="Iris-setosa":
        x=0
    elif x=="Iris-versicolor":
        x=1
    return x
data['Species'] = data['Species'].apply(convert)

In [208]:
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [209]:
data['Species'].value_counts()

0                 50
1                 50
Iris-virginica    50
Name: Species, dtype: int64

In [210]:
X = data.iloc[:100,:-1].values
y = data.iloc[:100,-1].values

In [211]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [212]:
X

array([[  1. ,   5.1,   3.5,   1.4,   0.2],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [  3. ,   4.7,   3.2,   1.3,   0.2],
       [  4. ,   4.6,   3.1,   1.5,   0.2],
       [  5. ,   5. ,   3.6,   1.4,   0.2],
       [  6. ,   5.4,   3.9,   1.7,   0.4],
       [  7. ,   4.6,   3.4,   1.4,   0.3],
       [  8. ,   5. ,   3.4,   1.5,   0.2],
       [  9. ,   4.4,   2.9,   1.4,   0.2],
       [ 10. ,   4.9,   3.1,   1.5,   0.1],
       [ 11. ,   5.4,   3.7,   1.5,   0.2],
       [ 12. ,   4.8,   3.4,   1.6,   0.2],
       [ 13. ,   4.8,   3. ,   1.4,   0.1],
       [ 14. ,   4.3,   3. ,   1.1,   0.1],
       [ 15. ,   5.8,   4. ,   1.2,   0.2],
       [ 16. ,   5.7,   4.4,   1.5,   0.4],
       [ 17. ,   5.4,   3.9,   1.3,   0.4],
       [ 18. ,   5.1,   3.5,   1.4,   0.3],
       [ 19. ,   5.7,   3.8,   1.7,   0.3],
       [ 20. ,   5.1,   3.8,   1.5,   0.3],
       [ 21. ,   5.4,   3.4,   1.7,   0.2],
       [ 22. ,   5.1,   3.7,   1.5,   0.4],
       [ 23. ,   4.6,   3.6,   1

In [213]:
X = X[:,1:]

In [214]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [215]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)


In [216]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [217]:
class Perceptron_adam:
    def __init__(self, learning_rate=0.001, num_epochs=2000, decay_rate=0.9, epsilon=1e-7):
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
        self.decay_rate = decay_rate
        self.epsilon = epsilon
        self.moving_avg_sq_b = 0
        self.moving_avg_sq_w = 0
        

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def sigmoid_prime(self, z):
        return self.sigmoid(z) * (1 - self.sigmoid(z))

    def predicted(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        pred = self.sigmoid(linear_model)
        return pred

    def sigmoid_prime_predictor(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        pred = self.sigmoid_prime(linear_model)
        return pred

    def fit(self, X, y):
        
        num_samples, num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0
        
        for i in range(self.num_epochs):
            y_pred = self.predicted(X)
            sp = self.sigmoid_prime_predictor(X)
            term = ((y_pred - y) * sp).astype('float')
            dw = (1 / num_samples) * np.dot(X.T, term)
            db = (1 / num_samples) * sum(term)

            # Update the moving average of squared gradients
            self.moving_avg_sq_w = self.decay_rate * self.moving_avg_sq_w + (1 - self.decay_rate) * (dw ** 2)
            self.moving_avg_sq_b = self.decay_rate * self.moving_avg_sq_b + (1 - self.decay_rate) * (db ** 2)
            
            # Update weights and bias using  rmsprop
            self.weights -= (self.learning_rate / (np.sqrt((self.moving_avg_sq_w) + self.epsilon))) * dw
            self.bias -= (self.learning_rate / (np.sqrt((self.moving_avg_sq_b) + self.epsilon))) * db

    def test(self, X, y):
        Y_predtest = self.predicted(X)
        Y_values = Y_predtest
        correct = 0
        total = len(y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i] > 0.5:
                Y_predtest[i] = 1
            else:
                Y_predtest[i] = 0
        for i in range(len(y)):
            if y[i] == Y_predtest[i]:
                correct += 1
        print("Accuracy is : ",correct/total)
        return Y_predtest


In [218]:
class Perceptron:
    def __init__(self,learning_rate=0.01,num_epochs=1000):
        self.learning_rate = learning_rate
        self.num_epochs = num_epochs
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))

    def sigmoid_prime(self,z):
        return self.sigmoid(z)*(1-self.sigmoid(z))
    
    def predicted(self,X):
        # print(X.shape)
        # print(self.bias)
        # print(self.weights.shape)
        linear_model = np.dot(X,self.weights)+self.bias
        # print(linear_model.shape)
        pred = self.sigmoid(linear_model)
        return pred
    
    def sigmoid_prime_predictor(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        pred = self.sigmoid_prime(linear_model)
        return pred
    
    def fit(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.array([0.0]*num_features,dtype="float64")
        # print(self.weights.dtype)
        self.bias = 0 

        for i in range(self.num_epochs):
            y_pred = self.predicted(X)
            # print(y_pred.shape)
            # print("Prediction type : ",y_pred.dtype)
            sp = self.sigmoid_prime_predictor(X)
            # print("Sp type :",sp.dtype)
            term = ((y_pred - y)*sp).astype('float')
            # print("Subtraction type : ",(y_pred-y).dtype)
            # print("Term type : ",term.dtype)
            dw = (1/num_samples)*np.dot(X.T,term)
            # print(dw.dtype)
            db = (1/num_samples)*sum(term)

            self.weights -= self.learning_rate*dw
            self.bias -= self.learning_rate*db
    
    def test(self,X,y):
        global Y_predtest
        Y_predtest = self.predicted(X)
        print(Y_predtest)
        Y_values = Y_predtest
        correct = 0
        total = len(y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i]>0.5:
                Y_predtest[i] =1
            else:
                Y_predtest[i]=0
        for i in range(len(y)):
            if y[i] == Y_predtest[i]:
                correct+=1

        print("Accuracy: ",correct/total) 
        return Y_predtest
            

            

In [219]:
lgreg = Perceptron()
lgreg.fit(X_train,y_train)

In [220]:
print(lgreg.weights)
print(lgreg.bias)

[ 0.3638132  -0.38362432  0.53649734  0.53455321]
0.049369040034941476


In [221]:
y_predicted = lgreg.test(X_test, y_test)
print(y_predicted)

[0.91540496 0.84965915 0.88186361 0.26258445 0.23134809 0.22968047
 0.13639333 0.803272   0.22170002 0.21054432 0.2711261  0.24418423
 0.86646631 0.16611415 0.82489307 0.18841473 0.92523877 0.93324716
 0.22942949 0.30028304]
Accuracy:  1.0
[1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0.]


In [222]:
print(y_test)

[1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 1 0 0]


In [223]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test,y_predicted)
print(acc)

ValueError: Classification metrics can't handle a mix of unknown and binary targets

In [ ]:
arr = np.array([1,2])
arr2 = np.array([3,4])
print(arr*arr2)

In [ ]:
print(np.sum(arr+arr2))