In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('Iris.csv')

In [3]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [191]:
def convert(x):
    if x == 'Iris-setosa':
        x = 0
    elif x == 'Iris-versicolor':
        x = 1
    return x

df['Species'] = df['Species'].apply(convert)
df      

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [192]:
X = df.iloc[:100,:-1].values
y = df.iloc[:100,-1].values
X

array([[  1. ,   5.1,   3.5,   1.4,   0.2],
       [  2. ,   4.9,   3. ,   1.4,   0.2],
       [  3. ,   4.7,   3.2,   1.3,   0.2],
       [  4. ,   4.6,   3.1,   1.5,   0.2],
       [  5. ,   5. ,   3.6,   1.4,   0.2],
       [  6. ,   5.4,   3.9,   1.7,   0.4],
       [  7. ,   4.6,   3.4,   1.4,   0.3],
       [  8. ,   5. ,   3.4,   1.5,   0.2],
       [  9. ,   4.4,   2.9,   1.4,   0.2],
       [ 10. ,   4.9,   3.1,   1.5,   0.1],
       [ 11. ,   5.4,   3.7,   1.5,   0.2],
       [ 12. ,   4.8,   3.4,   1.6,   0.2],
       [ 13. ,   4.8,   3. ,   1.4,   0.1],
       [ 14. ,   4.3,   3. ,   1.1,   0.1],
       [ 15. ,   5.8,   4. ,   1.2,   0.2],
       [ 16. ,   5.7,   4.4,   1.5,   0.4],
       [ 17. ,   5.4,   3.9,   1.3,   0.4],
       [ 18. ,   5.1,   3.5,   1.4,   0.3],
       [ 19. ,   5.7,   3.8,   1.7,   0.3],
       [ 20. ,   5.1,   3.8,   1.5,   0.3],
       [ 21. ,   5.4,   3.4,   1.7,   0.2],
       [ 22. ,   5.1,   3.7,   1.5,   0.4],
       [ 23. ,   4.6,   3.6,   1

In [193]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [194]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.25,random_state=42)
print(X_train.shape)
print(type(X_train))

(75, 5)
<class 'numpy.ndarray'>


In [195]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)


In [196]:
X_train

array([[0.14285714, 0.51851852, 1.        , 0.10526316, 0.2       ],
       [0.39795918, 0.25925926, 0.625     , 0.05263158, 0.13333333],
       [0.96938776, 0.51851852, 0.375     , 0.81578947, 0.8       ],
       [0.08163265, 0.22222222, 0.45833333, 0.10526316, 0.        ],
       [0.7244898 , 0.74074074, 0.20833333, 1.        , 0.93333333],
       [0.10204082, 0.18518519, 0.58333333, 0.13157895, 0.06666667],
       [0.46938776, 0.11111111, 0.5       , 0.07894737, 0.06666667],
       [0.85714286, 0.62962963, 0.58333333, 0.89473684, 1.        ],
       [0.2755102 , 0.33333333, 0.58333333, 0.07894737, 0.06666667],
       [0.93877551, 0.25925926, 0.125     , 0.57894737, 0.6       ],
       [0.04081633, 0.40740741, 0.79166667, 0.15789474, 0.2       ],
       [0.66326531, 0.48148148, 0.41666667, 0.89473684, 0.93333333],
       [0.65306122, 0.88888889, 0.45833333, 0.86842105, 0.86666667],
       [0.34693878, 0.25925926, 0.5       , 0.02631579, 0.06666667],
       [0.15306122, 0.40740741, 0.

In [197]:
X_test

array([[0.92222222, 0.66666667, 0.21052632, 1.        , 0.88235294],
       [0.58888889, 0.45833333, 0.        , 0.73170732, 0.70588235],
       [0.77777778, 0.625     , 0.47368421, 0.92682927, 1.        ],
       [0.5       , 0.16666667, 0.36842105, 0.09756098, 0.11764706],
       [0.48888889, 0.29166667, 0.78947368, 0.2195122 , 0.17647059],
       [0.43333333, 0.29166667, 0.57894737, 0.12195122, 0.05882353],
       [0.24444444, 0.08333333, 0.68421053, 0.        , 0.05882353],
       [0.88888889, 0.45833333, 0.05263158, 0.68292683, 0.58823529],
       [0.11111111, 0.41666667, 0.73684211, 0.12195122, 0.05882353],
       [0.        , 0.29166667, 0.63157895, 0.09756098, 0.05882353],
       [0.2       , 0.54166667, 0.78947368, 0.17073171, 0.11764706],
       [0.33333333, 0.16666667, 0.42105263, 0.14634146, 0.05882353],
       [0.81111111, 0.70833333, 0.26315789, 0.90243902, 0.64705882],
       [0.36666667, 0.45833333, 1.        , 0.09756098, 0.05882353],
       [1.        , 0.45833333, 0.

In [198]:
Y_test

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 1], dtype=object)

In [199]:
class perceptron:
    def __init__(self,learning_rate=0.01,iterations=10000,batch_size=25):
        self.learning_rate = learning_rate
        self.iterations =  iterations
        self.batch_size = batch_size
    
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def predicted(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        pred = self.sigmoid(linear_model)
        return pred
    
    def sigmoid_prime(self,X):
        linear_model = np.dot(X,self.weights)+self.bias
        return self.sigmoid(linear_model)*(1-self.sigmoid(linear_model))
    
    def fit_stochastic(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.zeros(num_features)
        print(self.weights.shape)
        self.bias = 0
        for i in range(self.iterations):
            for j in range(num_samples):
                y_pred = self.predicted(X[j])    
                loss = (y_pred - y[j])
                term = (loss*self.sigmoid_prime(X[j])).astype(float)
                dw = (1/num_samples)*(np.dot(X[j],term))
                db = (1/num_samples)*term
            
                self.weights -= self.learning_rate*dw
                self.bias -= self.learning_rate*db
    def nesterov_prime(self,X):
        linear_model = np.dot(X,self.future_weights)+ self.future_bias
        return self.sigmoid(linear_model)*(1-self.sigmoid(linear_model))
    
    def fit_momentum(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0
        prev_v_w,prev_v_b,gamma = 0,0,0.9
        for i in range(self.iterations):
            for j in range(num_samples):
                y_pred = self.predicted(X[j])
                loss = (y_pred - y[j])
                term = (loss*self.sigmoid_prime(X[j])).astype(float)
                dw = (1/num_samples)*(np.dot(X[j],term))
                db = (1/num_samples)*term
                v_w = -gamma*prev_v_w + self.learning_rate*dw
                v_b = -gamma*prev_v_b + self.learning_rate*db
                self.weights-=v_w
                self.bias-=v_b
                prev_v_w = v_w
                prev_v_b = v_b
    
    def fit_nestorov(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0
        prev_v_w,prev_v_b,gamma = 0,0,0.9
        
        for i in range(self.iterations):
            for j in range(num_samples):
                v_w = -gamma*prev_v_w
                v_b = -gamma*prev_v_b
                self.future_weights = self.weights - v_w
                self.future_bias = self.bias - v_b
                y_pred = self.predicted(X[j])
                loss = (y_pred - y[j])
                term = (loss*self.nesterov_prime(X[j])).astype(float)
                dw = (1/num_samples)*(np.dot(X[j],term))
                db = (1/num_samples)*term
                v_w = -gamma*prev_v_w + self.learning_rate*dw
                v_b = -gamma*prev_v_b + self.learning_rate*db
                self.weights-= v_w
                self.bias-= v_b
                prev_v_w = v_w
                prev_v_b = v_b
    
    def fit_adagrad(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0
        v_w = 0
        v_b = 0
        eps = 0.0000001
        for i in range(self.iterations):
            for j in range(num_samples):
                y_pred = self.predicted(X[j])
                loss = (y_pred - y[j])
                term = (loss*self.sigmoid_prime(X[j])).astype(float)
                dw = (1/num_samples)*(np.dot(X[j],term))
                db = (1/num_samples)*term
                v_w += dw**2
                v_b += db**2
                w = self.weights - (self.learning_rate/np.sqrt(v_w+eps))*dw
                b = self.bias - (self.learning_rate/np.sqrt(v_b+eps))*db
    
    def fit_rmsprop(self,X,y):
        num_samples,num_features = X.shape
        self.weights = np.zeros(num_features)
        self.bias = 0
        v_w = 0
        v_b = 0
        eps = 0.0000001
        beta1 = 0.9
        for i in range(self.iterations):
            for j in range(num_samples):
                y_pred = self.predicted(X[j])
                loss = (y_pred - y[j])
                term = (loss*self.sigmoid_prime(X[j])).astype(float)
                dw = (1/num_samples)*(np.dot(X[j],term))
                db = (1/num_samples)*term
                v_w = beta1*(v_w) + (1-beta1)*dw**2
                v_b = beta1*(v_b) + (1-beta1)*db**2
                w = self.weights - (self.learning_rate/np.sqrt(v_w+eps))*dw
                b = self.bias - (self.learning_rate/np.sqrt(v_b+eps))*db
        

   
    def test(self,X,y):
        global Y_predtest
        Y_predtest = self.predicted(X)
        Y_values = Y_predtest
        correct = 0
        total =len(y)
        for i in range(len(Y_predtest)):
            if Y_predtest[i]>0.5:
                Y_predtest[i] = 1
            else:
                Y_predtest[i]=0
        for i in range(len(y)):
            if y[i]==Y_predtest[i]:
                correct+=1
        
        print("Accuracy : ",correct/total) 
    

In [203]:
lgreg = perceptron()
lgreg.fit_momentum(X_train,Y_train)

In [204]:
print(lgreg.weights)
print(lgreg.bias)

[ 0.62799633  0.34421764 -0.87869146  1.06932694  1.05995478]
-0.7946648094331255


In [205]:
print(lgreg.test(X_test, Y_test))

Accuracy :  1.0
None
