In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [19]:
tf.__version__

'2.12.0'

In [5]:
df = pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [6]:
df = pd.get_dummies(df)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                      1                        0                       0  
1                      1                        0                       0  
2                      1                        0                       0  
3                      1                        0                       0  
4                      1                        0                       0  
..                   ...                      ...                     ...  
145                    0                        0                       1  
146                    0                        0                       1  
147                    0                        0                       1  
148                    0                        0                       1  
149                    0                        0                       1  

[150 rows x 8 columns]

In [7]:
X = df.iloc[:,:-3].values
y = df.iloc[:,-3:].values


In [8]:
X

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [9]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)

In [12]:
X_test

array([[0.47058824, 0.4375    , 0.375     , 0.60714286, 0.5       ],
       [0.06617647, 0.3125    , 1.        , 0.07142857, 0.09090909],
       [0.80147059, 0.9375    , 0.25      , 1.        , 1.        ],
       [0.50735294, 0.40625   , 0.4375    , 0.57142857, 0.63636364],
       [0.49264706, 0.65625   , 0.375     , 0.625     , 0.59090909],
       [0.16176471, 0.21875   , 0.75      , 0.03571429, 0.13636364],
       [0.40441176, 0.28125   , 0.4375    , 0.41071429, 0.54545455],
       [0.97058824, 0.6875    , 0.5625    , 0.67857143, 1.        ],
       [0.43382353, 0.46875   , 0.        , 0.57142857, 0.63636364],
       [0.53676471, 0.34375   , 0.3125    , 0.46428571, 0.5       ],
       [0.74264706, 0.5625    , 0.625     , 0.67857143, 0.86363636],
       [0.02205882, 0.03125   , 0.5       , 0.01785714, 0.        ],
       [0.19852941, 0.25      , 0.8125    , 0.        , 0.04545455],
       [0.        , 0.0625    , 0.5625    , 0.03571429, 0.        ],
       [0.07352941, 0.125     , 1.

In [13]:
y_train

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1,

In [14]:
y_test.shape

(30, 3)

## Building the ANN

In [15]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units =3,activation = 'softmax'))



In [16]:
ann.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [17]:
ann.fit(X_train, y_train,batch_size=32,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0947 - accuracy: 0.3333
Epoch 2/100
4/4 [==============================] - 0s 754us/step - loss: 1.0887 - accuracy: 0.3333
Epoch 3/100
4/4 [==============================] - 0s 599us/step - loss: 1.0833 - accuracy: 0.3333
Epoch 4/100
4/4 [==============================] - 0s 705us/step - loss: 1.0781 - accuracy: 0.3333
Epoch 5/100
4/4 [==============================] - 0s 751us/step - loss: 1.0727 - accuracy: 0.3333
Epoch 6/100
4/4 [==============================] - 0s 650us/step - loss: 1.0678 - accuracy: 0.3333
Epoch 7/100
4/4 [==============================] - 0s 707us/step - loss: 1.0631 - accuracy: 0.3333
Epoch 8/100
4/4 [==============================] - 0s 669us/step - loss: 1.0583 - accuracy: 0.3333
Epoch 9/100
4/4 [==============================] - 0s 642us/step - loss: 1.0535 - accuracy: 0.3333
Epoch 10/100
4/4 [==============================] - 0s 684us/step - loss: 1.0483 - accuracy: 0.3333


2023-10-26 00:46:12.818265: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


Epoch 11/100
4/4 [==============================] - 0s 762us/step - loss: 1.0429 - accuracy: 0.3333
Epoch 12/100
4/4 [==============================] - 0s 711us/step - loss: 1.0366 - accuracy: 0.3333
Epoch 13/100
4/4 [==============================] - 0s 601us/step - loss: 1.0304 - accuracy: 0.3333
Epoch 14/100
4/4 [==============================] - 0s 949us/step - loss: 1.0241 - accuracy: 0.3333
Epoch 15/100
4/4 [==============================] - 0s 872us/step - loss: 1.0178 - accuracy: 0.3333
Epoch 16/100
4/4 [==============================] - 0s 582us/step - loss: 1.0112 - accuracy: 0.3333
Epoch 17/100
4/4 [==============================] - 0s 550us/step - loss: 1.0051 - accuracy: 0.3333
Epoch 18/100
4/4 [==============================] - 0s 566us/step - loss: 0.9992 - accuracy: 0.3500
Epoch 19/100
4/4 [==============================] - 0s 747us/step - loss: 0.9934 - accuracy: 0.3833
Epoch 20/100
4/4 [==============================] - 0s 938us/step - loss: 0.9876 - accuracy: 0.4000


In [18]:
y_pred = ann.predict(X_test)
print(y_pred)

1/1 [==============================] - 0s 30ms/step
[[0.14201318 0.4918433  0.36614352]
 [0.9850612  0.00463992 0.01029884]
 [0.12158908 0.49225697 0.38615388]
 [0.16340844 0.44363156 0.39296007]
 [0.13803816 0.48167062 0.38029128]
 [0.9695547  0.01086881 0.01957647]
 [0.3280517  0.34236532 0.329583  ]
 [0.20882918 0.3006923  0.49047852]
 [0.12761064 0.5516614  0.32072797]
 [0.20086011 0.45507175 0.34406808]
 [0.19696058 0.34949774 0.45354173]
 [0.9406509  0.02649871 0.03285037]
 [0.98288584 0.00595939 0.0111549 ]
 [0.9486715  0.02200305 0.02932548]
 [0.9866079  0.00431924 0.00907294]
 [0.22172168 0.36033037 0.41794798]
 [0.1570142  0.4007243  0.44226143]
 [0.15053615 0.5024089  0.34705496]
 [0.14629458 0.49521562 0.35848984]
 [0.16473648 0.37783515 0.45742834]
 [0.9517692  0.02048409 0.02774668]
 [0.22064722 0.35497925 0.4243736 ]
 [0.96551406 0.01276199 0.02172399]
 [0.16252966 0.38883957 0.4486307 ]
 [0.21019182 0.30988178 0.47992638]
 [0.19165099 0.30795825 0.5003907 ]
 [0.13442105