In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [80]:
df = pd.read_csv('iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [81]:
df = pd.get_dummies(df)
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica  
0                      1                        0                       0  
1                      1                        0                       0  
2                      1                        0                       0  
3                      1                        0                       0  
4                      1                        0                       0  
..                   ...                      ...                     ...  
145                    0                        0                       1  
146                    0                        0                       1  
147                    0                        0                       1  
148                    0                        0                       1  
149                    0                        0                       1  

[150 rows x 8 columns]

In [82]:
X = df.iloc[:,:-3].values
y = df.iloc[:,-3:].values


In [83]:
X

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [84]:
y

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0,

In [85]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [86]:
from sklearn.preprocessing import MinMaxScaler
ms = MinMaxScaler()
X_train = ms.fit_transform(X_train)
X_test = ms.fit_transform(X_test)

In [87]:
X_test

array([[0.47058824, 0.4375    , 0.375     , 0.60714286, 0.5       ],
       [0.06617647, 0.3125    , 1.        , 0.07142857, 0.09090909],
       [0.80147059, 0.9375    , 0.25      , 1.        , 1.        ],
       [0.50735294, 0.40625   , 0.4375    , 0.57142857, 0.63636364],
       [0.49264706, 0.65625   , 0.375     , 0.625     , 0.59090909],
       [0.16176471, 0.21875   , 0.75      , 0.03571429, 0.13636364],
       [0.40441176, 0.28125   , 0.4375    , 0.41071429, 0.54545455],
       [0.97058824, 0.6875    , 0.5625    , 0.67857143, 1.        ],
       [0.43382353, 0.46875   , 0.        , 0.57142857, 0.63636364],
       [0.53676471, 0.34375   , 0.3125    , 0.46428571, 0.5       ],
       [0.74264706, 0.5625    , 0.625     , 0.67857143, 0.86363636],
       [0.02205882, 0.03125   , 0.5       , 0.01785714, 0.        ],
       [0.19852941, 0.25      , 0.8125    , 0.        , 0.04545455],
       [0.        , 0.0625    , 0.5625    , 0.03571429, 0.        ],
       [0.07352941, 0.125     , 1.

In [88]:
y_train

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1,

## Building the ANN

In [89]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6,activation='relu'))
ann.add(tf.keras.layers.Dense(units = 6,activation = 'relu'))
ann.add(tf.keras.layers.Dense(units =3,activation = 'softmax'))



In [90]:
ann.compile(optimizer='Adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [91]:
ann.fit(X_train, y_train,batch_size=32,epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 797us/step - loss: 1.0793 - accuracy: 0.3667
Epoch 2/100
4/4 [==============================] - 0s 612us/step - loss: 1.0740 - accuracy: 0.3250
Epoch 3/100
4/4 [==============================] - 0s 503us/step - loss: 1.0698 - accuracy: 0.3250
Epoch 4/100
4/4 [==============================] - 0s 475us/step - loss: 1.0667 - accuracy: 0.3250
Epoch 5/100
4/4 [==============================] - 0s 515us/step - loss: 1.0636 - accuracy: 0.3250
Epoch 6/100
4/4 [==============================] - 0s 557us/step - loss: 1.0609 - accuracy: 0.3250
Epoch 7/100
4/4 [==============================] - 0s 625us/step - loss: 1.0580 - accuracy: 0.3250
Epoch 8/100
4/4 [==============================] - 0s 574us/step - loss: 1.0550 - accuracy: 0.3250
Epoch 9/100
4/4 [==============================] - 0s 533us/step - loss: 1.0516 - accuracy: 0.3250
Epoch 10/100
4/4 [==============================] - 0s 610us/step - loss: 1.0484 - accuracy: 0.3250
Epoch 11/

In [92]:
y_pred = ann.predict(X_test)
print(y_pred)

1/1 [==============================] - 0s 24ms/step
[[0.10658656 0.58433396 0.30907947]
 [0.95983    0.03808407 0.0020859 ]
 [0.00105065 0.11856759 0.8803817 ]
 [0.08379265 0.5605974  0.35560986]
 [0.04440649 0.48791355 0.46767992]
 [0.9452583  0.05191026 0.00283139]
 [0.25260943 0.57362664 0.17376393]
 [0.00441648 0.23391926 0.7616642 ]
 [0.02038081 0.34259698 0.6370222 ]
 [0.13273458 0.61417156 0.2530938 ]
 [0.02232881 0.406673   0.5709982 ]
 [0.93342686 0.0626194  0.00395372]
 [0.9589719  0.0392508  0.00177727]
 [0.9374283  0.05882809 0.00374362]
 [0.96509695 0.03318271 0.00172028]
 [0.16420339 0.5529809  0.28281572]
 [0.00603348 0.22803071 0.76593584]
 [0.13942976 0.60022295 0.26034728]
 [0.14859195 0.57898676 0.27242127]
 [0.00346835 0.1958734  0.80065817]
 [0.9430784  0.05393253 0.002989  ]
 [0.02627744 0.44080237 0.5329202 ]
 [0.94732183 0.04982881 0.00284934]
 [0.00432504 0.211926   0.783749  ]
 [0.01302104 0.37106276 0.6159162 ]
 [0.00353795 0.21019831 0.7862637 ]
 [0.00507089