In [ ]:
import numpy as np

class MLP:
    def __init__(self, input_size, hidden_size, output_size, learning_rate):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        # Initialize weights and biases for hidden and output layers
        self.hidden_weights = np.random.randn(self.input_size, self.hidden_size)
        self.hidden_weights1 = np.round(self.hidden_weights, 1)

        self.hidden_bias = np.random.randn(self.hidden_size)
        self.hidden_bias1 = np.round(self.hidden_bias, 1)

        self.output_weights = np.random.randn(self.hidden_size, self.output_size)
        self.output_weights1 = np.round(self.output_weights, 1)

        self.output_bias = np.random.randn(self.output_size)
        self.output_bias1 = np.round(self.output_bias, 1)

    def show(self):
      print(self.hidden_weights1)
      print(self.hidden_bias1)
      print(self.output_weights1)
      print(self.output_bias1)

    def forward(self, X):
        # Compute hidden layer output
        self.hidden_output = np.dot(X, self.hidden_weights1) + self.hidden_bias1
        self.hidden_activation = self.sigmoid(self.hidden_output)

        # Compute output layer output
        self.output = np.dot(self.hidden_activation, self.output_weights1) + self.output_bias1
        self.output_activation = self.sigmoid(self.output)

        return self.output_activation

    def backward(self, X, y, output):
        # Compute error and delta for output layer
        error = y - output
        output_delta = error * self.sigmoid_derivative(output)

        # Compute error and delta for hidden layer
        hidden_error = np.dot(output_delta, self.output_weights1.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.hidden_activation)

        # Update weights and biases for output and hidden layers
        self.output_weights1 += self.learning_rate * np.dot(self.hidden_activation.T, output_delta)
        self.output_bias1 += self.learning_rate * np.sum(output_delta, axis=0)
        self.hidden_weights1 += self.learning_rate * np.dot(X.T, hidden_delta)
        self.hidden_bias1 += self.learning_rate * np.sum(hidden_delta, axis=0)

    def train(self, X, y, epochs):
        for i in range(epochs):
            # Forward pass
            output = self.forward(X)

            # Backward pass
            self.backward(X, y, output)

            # Print loss for every 1000 epochs
            loss = np.mean(np.square(y - output))
            print(f"Epoch {i}, Loss: {loss:.4f}")

    def predict(self, X):
        return self.forward(X)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

In [ ]:
# Generate random input and output data
X = np.random.randn(2, 3)
X1 = np.round(X, 1)

y = np.random.randn(2, 1)
y1 = np.round(y, 1)

In [ ]:
# Create MLP with input size of 4, hidden size of 5, output size of 1, and learning rate of 0.1
mlp = MLP(3, 4, 1, 0.1)

In [ ]:
mlp.show()

[[ 1.2  0.5  0.6 -1.3]
 [-0.8  1.1  0.1  0.5]
 [ 0.3  1.9  0.8 -1.2]]
[ 0.7  0.8 -0.5 -0.7]
[[-1.2]
 [-0.4]
 [ 0.3]
 [-2. ]]
[-1.]


In [ ]:
mlp.train(X1, y1, 10)

Epoch 0, Loss: 0.2304
Epoch 1, Loss: 0.2298
Epoch 2, Loss: 0.2292
Epoch 3, Loss: 0.2285
Epoch 4, Loss: 0.2279
Epoch 5, Loss: 0.2272
Epoch 6, Loss: 0.2265
Epoch 7, Loss: 0.2258
Epoch 8, Loss: 0.2251
Epoch 9, Loss: 0.2244


In [ ]:
mlp.show()

[[ 1.20228191  0.50065779  0.59938129 -1.29647051]
 [-0.79941266  1.10006422  0.09974703  0.50044226]
 [ 0.30069734  1.90042621  0.80001175 -1.19792242]]
[ 0.68537874  0.79548495 -0.4963034  -0.72394704]
[[-1.16640994]
 [-0.36586006]
 [ 0.31877878]
 [-1.97941166]]
[-0.94663215]


In [ ]:
X1

array([[-0.3, -0.4,  0.6],
       [-0.1,  0.1, -0.3]])

In [ ]:
y1

array([[0.3],
       [0.7]])