In [1]:
import numpy as np

class MLP:
    def __init__(self, input_size, hidden_size, output_size, learning_rate):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        self.learning_rate = learning_rate

        # Initialize weights and biases for hidden and output layers
        self.hidden_weights = np.random.randn(self.input_size, self.hidden_size)
        self.hidden_weights1 = np.round(self.hidden_weights, 1)

        self.hidden_bias = np.random.randn(self.hidden_size)
        self.hidden_bias1 = np.round(self.hidden_bias, 1)

        self.output_weights = np.random.randn(self.hidden_size, self.output_size)
        self.output_weights1 = np.round(self.output_weights, 1)

        self.output_bias = np.random.randn(self.output_size)
        self.output_bias1 = np.round(self.output_bias, 1)

    def show(self):
      print(self.hidden_weights1)
      print(self.hidden_bias1)
      print(self.output_weights1)
      print(self.output_bias1)

    def forward(self, X):
        # Compute hidden layer output
        self.hidden_output = np.dot(X, self.hidden_weights1) + self.hidden_bias1
        self.hidden_activation = self.sigmoid(self.hidden_output)

        # Compute output layer output
        self.output = np.dot(self.hidden_activation, self.output_weights1) + self.output_bias1
        self.output_activation = self.sigmoid(self.output)

        return self.output_activation

    def backward(self, X, y, output):
        # Compute error and delta for output layer
        error = y - output
        output_delta = error * self.sigmoid_derivative(output)

        # Compute error and delta for hidden layer
        hidden_error = np.dot(output_delta, self.output_weights1.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.hidden_activation)

        # Update weights and biases for output and hidden layers
        self.output_weights1 += self.learning_rate * np.dot(self.hidden_activation.T, output_delta)
        self.output_bias1 += self.learning_rate * np.sum(output_delta, axis=0)
        self.hidden_weights1 += self.learning_rate * np.dot(X.T, hidden_delta)
        self.hidden_bias1 += self.learning_rate * np.sum(hidden_delta, axis=0)

    def train(self, X, y, epochs):
        for i in range(epochs):
            # Forward pass
            output = self.forward(X)

            # Backward pass
            self.backward(X, y, output)

            # Print loss for every 1000 epochs
            loss = np.mean(np.square(y - output))
            print(f"Epoch {i}, Loss: {loss:.4f}")

    def predict(self, X):
        return self.forward(X)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

In [2]:
# Generate random input and output data
X = np.random.randn(2, 3)
X1 = np.round(X, 1)

y = np.random.randn(2, 1)
y1 = np.round(y, 1)

In [3]:
# Create MLP with input size of 4, hidden size of 5, output size of 1, and learning rate of 0.1
mlp = MLP(3, 4, 1, 0.1)

In [4]:
mlp.show()

[[-1.3  0.2  1.5  0.2]
 [ 0.4 -0.6  1.3 -2.1]
 [-0.4 -0.2  1.4  0.5]]
[-1.9 -0.3  0.7  0.5]
[[ 0.9]
 [-1. ]
 [ 0.1]
 [ 1.5]]
[0.3]


In [5]:
mlp.train(X1, y1, 10)

Epoch 0, Loss: 0.1883
Epoch 1, Loss: 0.1804
Epoch 2, Loss: 0.1727
Epoch 3, Loss: 0.1652
Epoch 4, Loss: 0.1579
Epoch 5, Loss: 0.1508
Epoch 6, Loss: 0.1439
Epoch 7, Loss: 0.1373
Epoch 8, Loss: 0.1309
Epoch 9, Loss: 0.1248


In [6]:
mlp.show()

[[-1.30317351  0.23161891  1.49993833  0.15197261]
 [ 0.37843752 -0.56655883  1.29968448 -2.12800044]
 [-0.39449731 -0.19129926  1.40007069  0.47880103]]
[-1.91292626 -0.26305579  0.69980121  0.45542548]
[[ 0.87987774]
 [-1.05537998]
 [-0.06045438]
 [ 1.44885268]]
[0.13222416]


In [7]:
X1

array([[-0.1,  2.1, -0.8],
       [ 1.1,  0.6,  0.5]])

In [8]:
y1

array([[0.4],
       [0.1]])