In [72]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [73]:
df = pd.read_csv('../Datasets/Housing_data.csv')
df

Unnamed: 0       City     Price  Area                         Location  \
0               0  Bangalore  30000000  3340                 JP Nagar Phase 1   
1               1  Bangalore   7888000  1045       Dasarahalli on Tumkur Road   
2               2  Bangalore   4866000  1179  Kannur on Thanisandra Main Road   
3               3  Bangalore   8358000  1675                     Doddanekundi   
4               4  Bangalore   6845000  1670                          Kengeri   
...           ...        ...       ...   ...                              ...   
29130        7714     Mumbai  14500000  1180                   Mira Road East   
29131        7715     Mumbai  14500000   530                     Naigaon East   
29132        7716     Mumbai   4100000   700                         Shirgaon   
29133        7717     Mumbai   2750000   995                   Mira Road East   
29134        7718     Mumbai   2750000  1020                   Mira Road East   

       No. of Bedrooms  
0                    4  
1                    2  
2                    2  
3                    3  
4                    3  
...                ...  
29130                2  
29131                1  
29132                1  
29133                2  
29134                2  

[29135 rows x 6 columns]

In [52]:
df.nunique()

Unnamed: 0         7657
City                  6
Price              4924
Area               2452
Location           1776
No. of Bedrooms       9
dtype: int64

In [74]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['City'] = le.fit_transform(df['City'])
df['Location'] = le.fit_transform(df['Location'])

In [75]:
df

Unnamed: 0  City     Price  Area  Location  No. of Bedrooms
0               0     0  30000000  3340       595                4
1               1     0   7888000  1045       374                2
2               2     0   4866000  1179       698                2
3               3     0   8358000  1675       398                3
4               4     0   6845000  1670       731                3
...           ...   ...       ...   ...       ...              ...
29130        7714     5  14500000  1180       940                2
29131        7715     5  14500000   530       996                1
29132        7716     5   4100000   700      1491                1
29133        7717     5   2750000   995       940                2
29134        7718     5   2750000  1020       940                2

[29135 rows x 6 columns]

In [55]:
df.nunique()

Unnamed: 0         7657
City                  6
Price              4924
Area               2452
Location           1776
No. of Bedrooms       9
dtype: int64

In [77]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()

In [78]:
y = df['Price'].values

In [79]:
y

array([30000000,  7888000,  4866000, ...,  4100000,  2750000,  2750000])

In [80]:
df.drop(columns= ['Price'],inplace=True)
df

Unnamed: 0  City  Area  Location  No. of Bedrooms
0               0     0  3340       595                4
1               1     0  1045       374                2
2               2     0  1179       698                2
3               3     0  1675       398                3
4               4     0  1670       731                3
...           ...   ...   ...       ...              ...
29130        7714     5  1180       940                2
29131        7715     5   530       996                1
29132        7716     5   700      1491                1
29133        7717     5   995       940                2
29134        7718     5  1020       940                2

[29135 rows x 5 columns]

In [81]:
X = df.values

In [82]:
X

array([[   0,    0, 3340,  595,    4],
       [   1,    0, 1045,  374,    2],
       [   2,    0, 1179,  698,    2],
       ...,
       [7716,    5,  700, 1491,    1],
       [7717,    5,  995,  940,    2],
       [7718,    5, 1020,  940,    2]])

In [83]:
y

array([30000000,  7888000,  4866000, ...,  4100000,  2750000,  2750000])

In [84]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.2)

In [85]:
X_train

array([[2202,    4,  650, 1057,    2],
       [2388,    5,  840,  553,    2],
       [1878,    4, 1377,  869,    3],
       ...,
       [3610,    1,  637, 1110,    2],
       [ 967,    4, 1920,  412,    3],
       [1115,    1, 1229,  124,    3]])

In [86]:
Y_train

array([4000000, 5898000, 2200000, ..., 4770000, 7800000, 4914000])

In [87]:
dt.fit(X_train,Y_train)

DecisionTreeRegressor()

In [88]:
Y_pred = dt.predict(X_test)
Y_pred


array([ 2900000.,  6578000., 13500000., ..., 19000000.,  5300000.,
       14000000.])

In [89]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(Y_test,Y_pred)
mse

975496001504477.8